#!/bin/sh
# Sample simulator to Dakota system call script
# See Advanced Simulation Code Interfaces chapter in Users Manual

# $1 is params.in FROM Dakota
# $2 is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing ros.in
# Use the following line if SNL's APREPRO utility is used instead of DPrePro.
# ../aprepro -c '*' -q --nowarning ros.template ros.in


dprepro $1 transportProperties.template transportProperties.in
#dprepro $1 p.template p.in
#dprepro $1 fvSolution.template fvSolution.in

# --------
# ANALYSIS
# --------

pwd
cp -r ../casebase/* .
cp transportProperties.in constant/transportProperties
#cp p.in 0/p

blockMesh > log.blockmesh
pSwCoupledFoam > log.pSwCoupledFoam
sample -latestTime > log.sample

# ---------------
# POST-PROCESSING
# ---------------

#touch results.out
#cp ../casebase/results.out .

# Extract the last Injection rate
#tail -n 1 wellFlowRate/0/wellFlowRate.dat | cut -f3 > $2
# Extract saturation profile at injector
sed 's/.* //' sets/*/line_centreProfile_water.alpha.xy >> $2
