#!/bin/sh

# Build the mesh
echo "Building mesh ...\n"
cartesian2DMesh > log.createMesh

# Check its validity
echo "Checking mesh validity ...\n"
checkMesh       > log.checkMesh

# Copy initial files
cp -r 0.orig/* 0/

# Create high-K region
setSet -batch setSetCmd
setsToZones

# Set fields
setFields

# Run solver
impesFoam       | tee log.impesFoam
